name: Publish Authors Info Plugin
on:
  push:
    paths:
      - 'packages/author-info/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version to bump (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    uses: ./.github/workflows/publish-plugin-template.yml
    with:
      plugin-name: author-info
      version-type: ${{ inputs.version-type || 'patch' }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
